(fix) ErrorException when accessing PowerTrail details by OCTeam (#2448)
ErrorException: [/srv/ocpl/powerTrail.php:279] Trying to access array offset on false
/powerTrail.php?ptAction=showSerie&ptrail=
/powerTrail.php?ptAction=showSerie&ptrail=46
/powerTrail.php?ptAction=showSerie&ptrail=99999

- Added check for empty or invalid 'ptrail' parameter to prevent error when accessing PowerTrail details.
- Handled missing 'leadingUser' and 'ptOwners' for PowerTrail 46 and other cases.